apiVersion: v1
kind: Service
metadata:
  name: {{ include "operate.fullname" . }}
  labels: {{- include "operate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "operate.labels" . | nindent 4 }}
